### PR TITLE
Next

### PR DESCRIPTION
**Pull request by sccblom**
Two sets of bugs:
1. CADP
2. Explicit LTS with 4G+ edges
And one new feature
1. Weak bisimulation reduction and comparison.

### CODE REVIEW

**Comment by Meijuh** [comment]
@sccblom after some time I am now finally able to merge pull requests in a reliable way. I want to merge this one. There are three issues with this pull request right now
1. There is a commit with "untested" in the message, is this still a commit we want to have in LTSmin?
2. The Travis build right now fails, because there is a compile warning (which travis upgrades to an error).
3. You seem to have redefined DEBUG, as a Warning, which is always printed: https://github.com/utwente-fmt/ltsmin/pull/79/commits/e1ac7f0102b684f9442ec8259099386a7c660140#diff-ca3a818b85253d88df3163199565875fL11. Probably not intended?

Can you comment on these issues, or if you like fix them?

**Comment by sccblom** [comment]
Re 1. Ik heb maar 1 untested bedoeld achter gelaten en dat is over weak bisimulation. Die heb ik op het CWI geschreven en geport naar LTSmin, maar die is nooit uitgebreid getest.

Re 2. Als het geen suffe warning blijkt te zijn vraag het dan nog even na.

Re 3. Dat is niet de bedoeling.... leeft je uit en repareer het...

**Comment by Meijuh** [comment]
Ok ik zal deze commits zelf proberen te fixen.

**Comment by Meijuh** [comment]
I will cherry-pick these manually.

**Pull request closed without merging**
