### PR TITLE
Add GitHub CI

### PR DESCRIPTION
**Pull request by sockmaster27**

### CODE REVIEW

**Comment by jacopol** [comment]
In the final version, spins should not be disabled, I suppose?

**Comment by sockmaster27** [comment]
Runs `make check` on push and pull requests to master.
Currently appears to contain 1 failing test.

**Comment by jacopol** [comment]
OK, let's uncomment that failing test and sort it out later (after accepting the pull request)

**Comment by jacopol** [comment]
Thanks Holger, I have merged this now.
Just for the record, future work left:
- investigate this missing test
- run the test on other platforms than Ubuntu
- extend the test suite

**Pull request merged**
